exclude: "^docs/gitbook/"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: check-case-conflict
      - id: debug-statements
      - id: check-yaml

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
      - id: black
        language_version: python3.8

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.7.0
    hooks:
      - id: python-use-type-annotations
      - id: python-no-eval
      - id: python-no-log-warn

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest tests
        language: system
        pass_filenames: false
        # alternatively you could `types: [python]` so it only runs when python files change
        # though tests might be invalidated if you were to say change a data file
        always_run: true

      - id: flakeheaven
        name: flakeheaven
        entry: poetry run flakeheaven lint
        language: system
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: poetry run mypy .
        language: system
        pass_filenames: false

