name: Linting

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v4

      - name: Install dev packages
        run: poetry install -n -v

      - name: Lint with flakeheaven
        run: poetry run flakeheaven lint

      - name: Lint with black
        run: poetry run black . --check

      - name: Lint with isort
        run: poetry run isort . --check

      - name: Lint with mypy
        run: poetry run mypy .
