name: Linting

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          poetry install -D
      - name: Lint with flakehell
        run: |
          flakehell lint

      - name: Lint with black
        run: |
          black --check .

      - name: Lint with isort
        run: |
          isort --check .
